{{- if .Values.gateway.enabled -}}
{{- $fullName := include "go-hello-world.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $gatewayName := .Values.gateway.name | default (printf "%s-gateway" $fullName) -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "go-hello-world.labels" . | nindent 4 }}
  {{- with .Values.gateway.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.gateway.create }}
  parentRefs:
    - name: {{ $gatewayName }}
  {{- else }}
  parentRefs:
    - name: {{ $gatewayName }}
      {{- if .Values.gateway.namespace }}
      namespace: {{ .Values.gateway.namespace }}
      {{- end }}
  {{- end }}
  {{- with .Values.gateway.httpRoute.hostnames }}
  hostnames:
    {{- range . }}
    - {{ tpl . $ | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.gateway.httpRoute.rules }}
    - matches:
        {{- range .matches }}
        - path:
            type: {{ .path.type | default "PathPrefix" }}
            value: {{ .path.value | quote }}
          {{- if .method }}
          method: {{ .method }}
          {{- end }}
          {{- if .headers }}
          headers:
            {{- toYaml .headers | nindent 12 }}
          {{- end }}
          {{- if .queryParams }}
          queryParams:
            {{- toYaml .queryParams | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- if .filters }}
      filters:
        {{- toYaml .filters | nindent 8 }}
      {{- end }}
      backendRefs:
        {{- if .backendRefs }}
        {{- toYaml .backendRefs | nindent 8 }}
        {{- else }}
        - name: {{ $fullName }}
          port: {{ $svcPort }}
          {{- if .weight }}
          weight: {{ .weight }}
          {{- end }}
        {{- end }}
    {{- end }}
{{- end }}
